#!/bin/sh
# (c) Viator 2009
# Mplayer Scrobble Script
# Example: mplayer [parameters] song | pipescrobbler
#
# Install lastfmsubmitd &&
# cd ~/bin && ln -s /usr/lib/lastfmsubmitd/lastfmsubmit lastfm
#
# Russian language scrobbler only
#



artist=""
title=""
album=""
genre=""
isradio="False"
website=""

while true
do
  if read info
    then      
      #echo "$info" Playing PAUSE Volume      
      tmp=`echo $info | grep "PAUSE"`
      if [ "$tmp" != ""  ]
        then
          echo "$tmp"
      fi
      tmp=`echo $info | grep "ПРИОСТАНОВЛЕНО"`
      if [ "$tmp" != ""  ]
        then
          echo "$tmp"
      fi
      tmp=`echo $info | grep "Громкость"`
      if [ "$tmp" != ""  ]
        then
          echo "$tmp"
      fi
      tmp=`echo $info | grep "Volume"`
      if [ "$tmp" != ""  ]
        then
          echo "$tmp"
      fi
      tmp=`echo $info | grep "Воспроизведение"`
      if [ "$tmp" != ""  ]
        then
          file=`echo $tmp | sed -e "s/Воспроизведение\ //"`
      fi
      tmp=`echo $info | grep "Playing"`
      if [ "$tmp" != ""  ]
        then
          file=`echo $tmp | sed -e "s/Playing\ //"`
      fi
      tmp=`echo $info | grep "Title: " | sed -e "s/Title:\ //"`
      if [ "$tmp" != "" ]        
        then
          title="$tmp"
          isradio="False"
      fi
      tmp=`echo $info | grep "Genre"`
      if [ "$tmp" != "" ]
        then
          genre="$tmp"
      fi
      tmp=`echo $info | grep "Artist: " | sed -e "s/Artist:\ //"`
      if [ "$tmp" != "" ]
        then
          artist="$tmp"          
          isradio="False"
      fi
      tmp=`echo $info | grep "Album: " | sed -e "s/Album:\ //"`
      if [ "$tmp" != "" ]
        then
          album="$tmp"          
          isradio="False"
      fi      
      tmp=`echo $info | grep "Website: " | sed -e "s/Website:\ //"`
      if [ "$tmp" != "" ]
        then
          website="$tmp"          
      fi      
      ICY=`echo $info | grep "ICY Info:"`
      if [ "$ICY" != "" ]
        then
          title=`echo $ICY | sed -e "s/ICY\ Info:\ StreamTitle='//" | sed -e "s/';StreamUrl=//" | sed -e "s/''//" | sed -e "s/;//"`
          artist="[STREAM]"
          show="True"
          isradio="True"      
      fi
      tmp=`echo $info | grep "Начало воспроизведения"`
      if [ "$tmp" != "" ]
        then 
          if [ "$isradio" = "True" ] 
            then show="False"
            else show="True"
          fi        
      fi
      if [ "$show" = "True" ]
        then          
          show="False"
          if [ "$artist" = "" ] 
            then
              artist="Unknown"
          fi
          if [ "$genre" = "" ]
            then 
              genre="Unknown"
          fi
          if [ "$title" = "" ]
            then
              title=`basename "$file"`
              title=`echo "$title" | sed -e "s/.mp3//"`
          fi        
          if [ "$album" = "" ] 
            then
              album="Unknown"
          fi     
          # отправляем на ластфм
          lastfm --artist "$artist" --title "$title" --album "$album" --length "500"          
          #echo "Scrobbled: $artist - $title - $album"
          echo `date`' : '
          echo "/me is listening: $artist - $title [$genre]"
          if [ -z "$DISPLAY" ] 
            then              
              echo "NO ACTIVE DISPLAY"
            else               
              # Тут можно настроить свои собственные нотисы-команды, котоыре вам нужны
            #  tkabber_setstatus "mplayer: $artist - $title [$genre]"
#              echo "/me is listening: $artist - $title [$genre]" | xclip
              sendxmobar "<fc=#35bdb5>$artist</fc> - <fc=#38bd35>$title</fc> <fc=#4840ed>[$genre]</fc>"
          fi          
          artist=""
          title=""
          album=""
          if [ "$isradio" != "True" ]
            then
              genre=""
          fi
      fi      
    else break
  fi
done

# END OF PIPE stdin

if [ -z "$DISPLAY" ]
  then
    echo "Stop playing..."
  else  
#    tkabber_setstatus ""
    sendxmobar ""
    echo "Stop playing..."
fi
