#!/usr/bin/python
# -*- coding: utf-8 -*-

#MPLAYERPIPECMD='pipecmdmpl'
#CMDMPL='mplayercmd'
#PID_PYMPLAYER='pymplayer.pid'
#PID_CTRLMPLD='ctrlmpld.pid'

#MPLAYERPIPECMD='/home/viator/.pipecmdmpl'
#MPLAYERSTDOUT='/home/viator/.mplout'

import os
import time
import sys
from config import *

print 'Stop pymplayer'
try:
    pidfile=open(PID_PYMPLAYER,'r')
    PID=pidfile.readline()
    PID=PID.replace('\n','')
    PID=int(PID)
    pidfile.close()
except:PID=0

try: SIGKILL = int(sys.argv[1])
except: SIGKILL = 2

try:
    if PID<>0: os.kill(PID,SIGKILL)
except: pass

time.sleep(1)
