#!/usr/bin/python
# -*- coding: utf-8 -*-

#MPLAYERPIPECMD='pipecmdmpl'
#CMDMPL='mplayercmd'
#PID_PYMPLAYER='pymplayer.pid'
#PID_CTRLMPLD='ctrlmpld.pid'

#MPLAYERPIPECMD='/home/viator/.pipecmdmpl'
#MPLAYERSTDOUT='/home/viator/.mplout'

import os
import time
from config import *

print 'Stoping mplayerd'

print 'Stop pymplayer'
try:    
    pidfile=open(PID_PYMPLAYER,'r')
    PID=pidfile.readline()
    PID=PID.replace('\n','')
    PID=int(PID)
    pidfile.close()
except:PID=0

try: 
    if PID<>0: os.kill(PID,2)
except: pass

time.sleep(1)

print 'Stop ctrlmpld'
try:
    pidfile=open(PID_CTRLMPLD,'r')
    PID=pidfile.readline()
    PID=PID.replace('\n','')
    PID=int(PID)
    pidfile.close()
except:PID=0

try: 
    if PID<>0: os.kill(PID,2)
except: pass

time.sleep(1)

#If you use windows, change it:

