#!/bin/sh
# Generate and Play list multimedia files in this directory with sort
# example: 
# cd ~/music
# mplaylist -R
# [playing music with Random-sort]

gen_mplayer_list > list.here
sort $* list.here > list.sort
lplay "list.sort"
