#!/usr/bin/python
# -*- coding: utf-8 -*-

from config import *
import sys

if len(sys.argv)>1:
    cmd = sys.argv[1]+' '
    cmd = cmd.strip()
    if len(sys.argv)>2:
        args=sys.argv[2:]
#        print '['+cmd+']'
        if (cmd=='p')or(cmd=='o')or(cmd=='loadfile')or(cmd=='loadlist'):
            cmd=cmd+' '
            for i in args:
                cmd = cmd+'"'+i+'"'+' '
        else:
            cmd=cmd+' '
            for i in args:
                cmd = cmd+i+' '
    cmd = cmd.strip()
#    print '['+cmd+']'
    cmd = cmd+'\n'
else: sys.exit()

f=open(MPLAYERPIPECMD,'w')
f.write(cmd)
f.close()
